# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pr: 
  - master
  - development
  - feature*
pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  branch: ''

stages: 
- stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    pool:
      vmImage: 'Ubuntu-latest'
    # creates an environment if it doesn't exist
    environment: manual-approval-test
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
  - job: Versioning
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          
          git config --global user.email "chanelyoung99@gmail.com"
          git config --global user.name "Chanel Young"
          
    - task: PowerShell@2
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
      displayName: 'building master'
      inputs:
        filePath: '$(Build.SourcesDirectory)/versioner.PS1'
    - task: PowerShell@2
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/development')
      displayName: 'building development'
      inputs:
        filePath: '$(Build.SourcesDirectory)/versioner.PS1'
        arguments: "minor"
    - task: PowerShell@2
      condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/feature')
      displayName: 'building feature branch'
      inputs:
        filePath: '$(Build.SourcesDirectory)/versioner.PS1'
        arguments: "minor"
