# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pr: 
  - master
  - development
  - feature/*
pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  branch: ''

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: PowerShell@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: 'building master'
  inputs:
    filePath: '$(Build.SourcesDirectory)/PipelineScripts/build.PS1'
    arguments: "master"
- task: PowerShell@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/development')
  displayName: 'building development'
  inputs:
    filePath: '$(Build.SourcesDirectory)/PipelineScripts/build.PS1'
    arguments: "development"
- task: PowerShell@2
  condition: and(ne(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.SourceBranch'], 'refs/heads/development'))
  displayName: 'building user branch'
  inputs:
    filePath: '$(Build.SourcesDirectory)/PipelineScripts/build.PS1'
    arguments: "user branch"