# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  tagUpdateLevel: 'minor'
  tagMessage: 'new feature'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email "chanelyoung99@gmail.com"
      git config --global user.name "Chanel Young"
      git config --global --add url."git@github.com:".insteadOf "https://github.com/"
- task: PowerShell@2
  inputs:
    filePath: '$(Build.SourcesDirectory)/versioner.PS1'
